import { prisma } from '../src/utils/prisma';

export async function seedDatabase() {
  console.log('--- Starting NOVA COMMAND Database Seeding ---');

  // Clear existing records in reverse relation order
  await prisma.workOrderSparePart.deleteMany();
  await prisma.maintenanceWorkOrder.deleteMany();
  await prisma.machineTelemetry.deleteMany();
  await prisma.operation.deleteMany();
  await prisma.qualityInspection.deleteMany();
  await prisma.inventoryTransaction.deleteMany();
  await prisma.purchaseOrder.deleteMany();
  await prisma.inventoryItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.machine.deleteMany();
  await prisma.employee.deleteMany();
  await prisma.alert.deleteMany();
  await prisma.decisionRecommendation.deleteMany();
  await prisma.whatIfScenario.deleteMany();
  await prisma.appUser.deleteMany();
  await prisma.systemState.deleteMany();

  // 1. Employees
  const employeesData = [
    {
      id: 'EMP-01',
      name: 'Marcus Vance',
      role: 'Senior Diagnostic Specialist & Mechatronics',
      skills: JSON.stringify(['CNC Vibration Diagnostics Level 3', 'Spindle Overhaul', 'Precision Alignment', 'Hydraulics']),
      shift: 'Shift A (06:00 - 14:00)',
      availability: 'available',
      workloadPct: 65,
      assignedLine: 'Line 2 - Stamping & Heavy Fabrication',
      hoursWorkedThisWeek: 32,
      avatarInitials: 'MV',
    },
    {
      id: 'EMP-02',
      name: 'Elena Chen',
      role: 'Lead 5-Axis CNC Machinist',
      skills: JSON.stringify(['5-Axis CNC Operation', 'Heidenhain Controller', 'CAD/CAM Post-Processing']),
      shift: 'Shift A (06:00 - 14:00)',
      availability: 'assigned',
      workloadPct: 88,
      assignedLine: 'Line 1 - High-Precision Milling',
      hoursWorkedThisWeek: 38,
      currentTaskId: 'OP-24',
      avatarInitials: 'EC',
    },
    {
      id: 'EMP-03',
      name: 'David Kalu',
      role: 'Maintenance Technician Level 2',
      skills: JSON.stringify(['Bearing Replacement', 'Pneumatics', 'Lubrication Systems', 'Safety Interlocks']),
      shift: 'Shift A (06:00 - 14:00)',
      availability: 'available',
      workloadPct: 45,
      assignedLine: 'Line 2 - Stamping & Heavy Fabrication',
      hoursWorkedThisWeek: 28,
      avatarInitials: 'DK',
    },
    {
      id: 'EMP-04',
      name: 'Aria Thorne',
      role: 'Senior Metrologist & Quality Lead',
      skills: JSON.stringify(['Zeiss Calypso CMM Programming', 'SPC Statistical Analysis', 'GD&T Certification', 'Surface Roughness Profilometry']),
      shift: 'Shift A (06:00 - 14:00)',
      availability: 'assigned',
      workloadPct: 92,
      assignedLine: 'Line 3 - Quality Assurance & Metrology',
      hoursWorkedThisWeek: 41,
      currentTaskId: 'OP-35',
      avatarInitials: 'AT',
    },
    {
      id: 'EMP-05',
      name: 'Tomasz Nowak',
      role: 'Automation & Robotics Engineer',
      skills: JSON.stringify(['Fanuc Robotic Cell Integration', 'PLC Troubleshooting', 'Safety Gate Interlocks']),
      shift: 'Shift B (14:00 - 22:00)',
      availability: 'available',
      workloadPct: 50,
      assignedLine: 'Line 2 - Stamping & Heavy Fabrication',
      hoursWorkedThisWeek: 20,
      avatarInitials: 'TN',
    },
    {
      id: 'EMP-06',
      name: 'Sarah Jenkins',
      role: 'Tooling Specialist & Cutter Presetting',
      skills: JSON.stringify(['Tool Pre-setter Zoller', 'Coating Analysis', 'Feed/Speed Optimization']),
      shift: 'Shift B (14:00 - 22:00)',
      availability: 'available',
      workloadPct: 60,
      assignedLine: 'Line 1 - High-Precision Milling',
      hoursWorkedThisWeek: 22,
      avatarInitials: 'SJ',
    },
    {
      id: 'EMP-07',
      name: 'Liam O’Connor',
      role: 'Production Scheduling Officer',
      skills: JSON.stringify(['MES Production Routing', 'Capacity Levelling', 'Lead-Time Modeling']),
      shift: 'Shift A (06:00 - 14:00)',
      availability: 'available',
      workloadPct: 70,
      assignedLine: 'Plant Operations Hub',
      hoursWorkedThisWeek: 35,
      avatarInitials: 'LO',
    },
    {
      id: 'EMP-08',
      name: 'Zoe Martinez',
      role: 'Inventory Logistics Coordinator',
      skills: JSON.stringify(['SAP ERP Material Master', 'Kaban Replenishment', 'Cycle Counting']),
      shift: 'Shift A (06:00 - 14:00)',
      availability: 'available',
      workloadPct: 55,
      assignedLine: 'Central Warehouse Bay 4',
      hoursWorkedThisWeek: 30,
      avatarInitials: 'ZM',
    },
    {
      id: 'EMP-09',
      name: 'Ravi Patel',
      role: 'CNC Precision Turning Technician',
      skills: JSON.stringify(['CNC Turning & Threading', 'Twin-Spindle Lathe Setup', 'Bore Micrometer Gauging']),
      shift: 'Shift A (06:00 - 14:00)',
      availability: 'assigned',
      workloadPct: 85,
      assignedLine: 'Line 1 - High-Precision Milling',
      hoursWorkedThisWeek: 36,
      currentTaskId: 'OP-31',
      avatarInitials: 'RP',
    },
    {
      id: 'EMP-10',
      name: 'Karin Lindqvist',
      role: 'Industrial Electrical Systems Engineer',
      skills: JSON.stringify(['Siemens Sinumerik 840D', 'High-Voltage Drives', 'Thermographic Inspection']),
      shift: 'Shift C (22:00 - 06:00)',
      availability: 'offline',
      workloadPct: 0,
      assignedLine: 'Plant Maintenance Hub',
      hoursWorkedThisWeek: 40,
      avatarInitials: 'KL',
    },
  ];

  for (const emp of employeesData) {
    await prisma.employee.create({ data: emp });
  }

  // 2. Machines and MachineTelemetry
  const machinesData = [
    {
      id: 'M-001',
      name: 'Hermle 5-Axis CNC Mill Alpha',
      line: 'Line 1 - High-Precision Milling',
      type: '5-Axis Machining Center',
      status: 'running',
      utilization: 94,
      healthScore: 96,
      temperature: 48.2,
      vibration: 1.82,
      vibrationThreshold: 3.2,
      energy: 42.5,
      currentOperationId: 'OP-24',
      currentOrderId: 'ORDER-1040',
      uptimeHours: 342,
      downtimeHours: 4.5,
      lastMaintenance: '2026-09-12',
      nextScheduledMaintenance: '2026-10-12',
      telemetry: [
        { timestamp: '10:00', temperature: 46.1, vibration: 1.75, energy: 41.2, rpm: 18000 },
        { timestamp: '11:00', temperature: 47.0, vibration: 1.78, energy: 42.0, rpm: 18000 },
        { timestamp: '12:00', temperature: 47.8, vibration: 1.80, energy: 42.1, rpm: 18000 },
        { timestamp: '13:00', temperature: 48.2, vibration: 1.82, energy: 42.5, rpm: 18000 },
      ],
    },
    {
      id: 'M-002',
      name: 'DMG Mori Precision Turning Lathe',
      line: 'Line 1 - High-Precision Milling',
      type: 'CNC Turning Center',
      status: 'running',
      utilization: 88,
      healthScore: 91,
      temperature: 51.4,
      vibration: 2.15,
      vibrationThreshold: 3.2,
      energy: 36.8,
      currentOperationId: 'OP-31',
      currentOrderId: 'ORDER-1043',
      uptimeHours: 298,
      downtimeHours: 8.2,
      lastMaintenance: '2026-09-04',
      nextScheduledMaintenance: '2026-10-04',
      telemetry: [
        { timestamp: '10:00', temperature: 49.5, vibration: 2.05, energy: 35.5, rpm: 6200 },
        { timestamp: '11:00', temperature: 50.2, vibration: 2.10, energy: 36.1, rpm: 6200 },
        { timestamp: '12:00', temperature: 51.0, vibration: 2.12, energy: 36.5, rpm: 6200 },
        { timestamp: '13:00', temperature: 51.4, vibration: 2.15, energy: 36.8, rpm: 6200 },
      ],
    },
    {
      id: 'M-003',
      name: 'Schuler Automated 500T Stamping Press',
      line: 'Line 2 - Stamping & Heavy Fabrication',
      type: 'Hydraulic Stamping Press',
      status: 'running',
      utilization: 82,
      healthScore: 89,
      temperature: 56.1,
      vibration: 2.41,
      vibrationThreshold: 3.5,
      energy: 78.4,
      currentOperationId: 'OP-32',
      currentOrderId: 'ORDER-1044',
      uptimeHours: 410,
      downtimeHours: 12.0,
      lastMaintenance: '2026-08-28',
      nextScheduledMaintenance: '2026-09-28',
      telemetry: [
        { timestamp: '10:00', temperature: 54.0, vibration: 2.30, energy: 76.0, rpm: 45 },
        { timestamp: '11:00', temperature: 54.8, vibration: 2.35, energy: 77.2, rpm: 45 },
        { timestamp: '12:00', temperature: 55.6, vibration: 2.39, energy: 78.0, rpm: 45 },
        { timestamp: '13:00', temperature: 56.1, vibration: 2.41, energy: 78.4, rpm: 45 },
      ],
    },
    {
      id: 'M-004',
      name: 'Makino Multi-Spindle High-Speed Milling Cell',
      line: 'Line 2 - Stamping & Heavy Fabrication',
      type: 'Multi-Spindle CNC Mill',
      status: 'warning',
      utilization: 61,
      healthScore: 54,
      temperature: 68.9,
      vibration: 4.85,
      vibrationThreshold: 3.2,
      energy: 58.6,
      currentOperationId: 'OP-27',
      currentOrderId: 'ORDER-1042',
      activeWorkOrderId: 'WO-204',
      uptimeHours: 182,
      downtimeHours: 24.6,
      lastMaintenance: '2026-08-15',
      nextScheduledMaintenance: '2026-09-27',
      criticalIssue: 'Abnormal spindle bearing vibration (+51.6% over prototype threshold of 3.2 mm/s). Micro-chatter impacting surface finish.',
      telemetry: [
        { timestamp: '09:00', temperature: 52.0, vibration: 2.95, energy: 44.0, rpm: 20000 },
        { timestamp: '10:00', temperature: 56.4, vibration: 3.42, energy: 47.8, rpm: 20000 },
        { timestamp: '11:00', temperature: 61.2, vibration: 3.98, energy: 52.1, rpm: 20000 },
        { timestamp: '12:00', temperature: 65.7, vibration: 4.45, energy: 56.0, rpm: 20000 },
        { timestamp: '13:00', temperature: 68.9, vibration: 4.85, energy: 58.6, rpm: 20000 },
      ],
    },
    {
      id: 'M-005',
      name: 'Zeiss Prismo Coordinate Measuring Machine (CMM)',
      line: 'Line 3 - Quality Assurance & Metrology',
      type: 'Coordinate Measuring System',
      status: 'running',
      utilization: 91,
      healthScore: 98,
      temperature: 20.8,
      vibration: 0.42,
      vibrationThreshold: 1.0,
      energy: 12.4,
      currentOperationId: 'OP-35',
      currentOrderId: 'ORDER-1040',
      uptimeHours: 520,
      downtimeHours: 1.2,
      lastMaintenance: '2026-09-18',
      nextScheduledMaintenance: '2026-10-18',
      telemetry: [
        { timestamp: '10:00', temperature: 20.6, vibration: 0.40, energy: 12.1, rpm: 0 },
        { timestamp: '11:00', temperature: 20.7, vibration: 0.41, energy: 12.3, rpm: 0 },
        { timestamp: '12:00', temperature: 20.8, vibration: 0.42, energy: 12.4, rpm: 0 },
        { timestamp: '13:00', temperature: 20.8, vibration: 0.42, energy: 12.4, rpm: 0 },
      ],
    },
    {
      id: 'M-006',
      name: 'Mazak Variaxis Standby 5-Axis Cell',
      line: 'Line 2 - Stamping & Heavy Fabrication',
      type: '5-Axis Machining Center (Flexible Standby)',
      status: 'running',
      utilization: 15,
      healthScore: 99,
      temperature: 32.1,
      vibration: 1.10,
      vibrationThreshold: 3.2,
      energy: 14.2,
      uptimeHours: 92,
      downtimeHours: 0.0,
      lastMaintenance: '2026-09-20',
      nextScheduledMaintenance: '2026-10-20',
      telemetry: [
        { timestamp: '10:00', temperature: 31.8, vibration: 1.05, energy: 13.9, rpm: 8000 },
        { timestamp: '11:00', temperature: 32.0, vibration: 1.08, energy: 14.1, rpm: 8000 },
        { timestamp: '12:00', temperature: 32.1, vibration: 1.10, energy: 14.2, rpm: 8000 },
        { timestamp: '13:00', temperature: 32.1, vibration: 1.10, energy: 14.2, rpm: 8000 },
      ],
    },
  ];

  for (const m of machinesData) {
    const { telemetry, ...machineFields } = m;
    await prisma.machine.create({ data: machineFields });
    for (const t of telemetry) {
      await prisma.machineTelemetry.create({
        data: {
          machineId: m.id,
          timestamp: t.timestamp,
          temperature: t.temperature,
          vibration: t.vibration,
          energy: t.energy,
          rpm: t.rpm,
        },
      });
    }
  }

  // 3. Orders
  const ordersData = [
    {
      id: 'ORDER-1042',
      customer: 'SkyVector Aerospace',
      product: 'Titanium Turbine Impeller Array v4',
      quantity: 120,
      valueUsd: 245000,
      orderDate: '2026-09-18',
      dueDate: '2026-09-27T18:00:00',
      status: 'in_production',
      materialReadiness: 'ready',
      machineReadiness: 'blocked',
      deliveryRisk: 'high',
      riskReasons: JSON.stringify([
        'Machine M-004 vibration anomaly throttled operation OP-27 by 5.5 hours',
        'Delivery buffer reduced to 1.5 hours before contractual SLA deadline',
        'High scrap risk if surface chatter exceeds 0.8 Ra tolerance',
      ]),
      currentOperationId: 'OP-27',
      penaltyPerDayUsd: 18500,
    },
    {
      id: 'ORDER-1048',
      customer: 'Nordic Defense Systems',
      product: 'Precision Gimbal Actuator Rotors',
      quantity: 85,
      valueUsd: 185000,
      orderDate: '2026-09-20',
      dueDate: '2026-09-28T12:00:00',
      status: 'planned',
      materialReadiness: 'ready',
      machineReadiness: 'at_risk',
      deliveryRisk: 'high',
      riskReasons: JSON.stringify([
        'Scheduled directly on M-004 after OP-27 (Operation OP-28 cascade delay)',
        'Estimated dispatch delay +7.2 hours if M-004 enters unscheduled breakdown',
      ]),
      currentOperationId: 'OP-28',
      penaltyPerDayUsd: 14000,
    },
    {
      id: 'ORDER-1040',
      customer: 'Apex Propulsion Corp',
      product: 'Stage 2 Turbine Housing',
      quantity: 50,
      valueUsd: 160000,
      orderDate: '2026-09-15',
      dueDate: '2026-09-29T16:00:00',
      status: 'in_production',
      materialReadiness: 'ready',
      machineReadiness: 'ready',
      deliveryRisk: 'low',
      riskReasons: JSON.stringify(['On track. Operation OP-24 progressing at 75% on M-001.']),
      currentOperationId: 'OP-24',
      penaltyPerDayUsd: 12000,
    },
    {
      id: 'ORDER-1043',
      customer: 'Quantum Dynamic Robotics',
      product: 'Hydraulic Core Cylinder',
      quantity: 220,
      valueUsd: 88000,
      orderDate: '2026-09-21',
      dueDate: '2026-09-30T10:00:00',
      status: 'in_production',
      materialReadiness: 'ready',
      machineReadiness: 'ready',
      deliveryRisk: 'low',
      riskReasons: JSON.stringify(['Nominal execution on M-002 lathe.']),
      currentOperationId: 'OP-31',
      penaltyPerDayUsd: 6500,
    },
    {
      id: 'ORDER-1044',
      customer: 'HyperLink Rail Transit',
      product: 'Coupling Flange Assembly',
      quantity: 400,
      valueUsd: 92000,
      orderDate: '2026-09-22',
      dueDate: '2026-10-01T17:00:00',
      status: 'in_production',
      materialReadiness: 'ready',
      machineReadiness: 'ready',
      deliveryRisk: 'low',
      riskReasons: JSON.stringify(['Press operations proceeding normally on M-003.']),
      currentOperationId: 'OP-32',
      penaltyPerDayUsd: 5000,
    },
    {
      id: 'ORDER-1045',
      customer: 'Stratos Satellite Labs',
      product: 'Beryllium Solar Gimbal Bracket',
      quantity: 30,
      valueUsd: 140000,
      orderDate: '2026-09-23',
      dueDate: '2026-10-02T14:00:00',
      status: 'planned',
      materialReadiness: 'partial',
      machineReadiness: 'ready',
      deliveryRisk: 'medium',
      riskReasons: JSON.stringify([
        'Raw material MAT-021 buffer at low reserve threshold (40 kg remaining)',
        'Dependent on PO-902 shipment arriving on schedule',
      ]),
      penaltyPerDayUsd: 15000,
    },
    {
      id: 'ORDER-1046',
      customer: 'Siemens Energy Solutions',
      product: 'Gas Turbine Stator Ring',
      quantity: 15,
      valueUsd: 310000,
      orderDate: '2026-09-12',
      dueDate: '2026-10-05T12:00:00',
      status: 'planned',
      materialReadiness: 'ready',
      machineReadiness: 'ready',
      deliveryRisk: 'low',
      riskReasons: JSON.stringify(['Nominal lead time margin +48 hours.']),
      penaltyPerDayUsd: 22000,
    },
    {
      id: 'ORDER-1047',
      customer: 'Valence Medical Devices',
      product: 'Titanium Surgical Robot Arm Links',
      quantity: 140,
      valueUsd: 195000,
      orderDate: '2026-09-24',
      dueDate: '2026-10-06T18:00:00',
      status: 'planned',
      materialReadiness: 'ready',
      machineReadiness: 'ready',
      deliveryRisk: 'low',
      riskReasons: JSON.stringify(['Scheduled on Line 1 with full material reservation.']),
      penaltyPerDayUsd: 16000,
    },
  ];

  for (const o of ordersData) {
    await prisma.order.create({ data: o });
  }

  // 4. Operations
  const operationsData = [
    {
      id: 'OP-24',
      name: 'Turbine Housing Rough Milling',
      orderId: 'ORDER-1040',
      machineId: 'M-001',
      line: 'Line 1 - High-Precision Milling',
      durationHours: 6.0,
      scheduledStart: '2026-09-26T08:00:00',
      scheduledEnd: '2026-09-26T14:00:00',
      status: 'in_progress',
      progressPct: 75,
      delayHours: 0,
      requiredSkill: '5-Axis CNC Operation',
    },
    {
      id: 'OP-27',
      name: 'AeroTurbine Impeller High-Speed Finishing',
      orderId: 'ORDER-1042',
      machineId: 'M-004',
      alternativeMachineId: 'M-006',
      line: 'Line 2 - Stamping & Heavy Fabrication',
      durationHours: 8.5,
      scheduledStart: '2026-09-26T13:30:00',
      scheduledEnd: '2026-09-26T22:00:00',
      status: 'delayed',
      progressPct: 15,
      delayHours: 5.5,
      delayReason: 'Throttled feed rate due to M-004 excessive spindle vibration (>4.8 mm/s). Risk of blade chatter defect.',
      requiredSkill: 'CNC High-Speed Spindle Operation',
    },
    {
      id: 'OP-28',
      name: 'Precision Rotor Balancing & Boring',
      orderId: 'ORDER-1048',
      machineId: 'M-004',
      alternativeMachineId: 'M-006',
      line: 'Line 2 - Stamping & Heavy Fabrication',
      durationHours: 6.0,
      scheduledStart: '2026-09-26T22:30:00',
      scheduledEnd: '2026-09-27T04:30:00',
      status: 'scheduled',
      progressPct: 0,
      delayHours: 4.0,
      delayReason: 'Queued behind delayed OP-27 on M-004.',
      requiredSkill: 'Precision Dynamic Balancing',
    },
    {
      id: 'OP-31',
      name: 'Hydraulic Cylinder Precision Turning',
      orderId: 'ORDER-1043',
      machineId: 'M-002',
      line: 'Line 1 - High-Precision Milling',
      durationHours: 4.5,
      scheduledStart: '2026-09-26T11:00:00',
      scheduledEnd: '2026-09-26T15:30:00',
      status: 'in_progress',
      progressPct: 60,
      delayHours: 0,
      requiredSkill: 'CNC Turning & Threading',
    },
    {
      id: 'OP-32',
      name: 'High-Strength Flange Stamping Pass 1',
      orderId: 'ORDER-1044',
      machineId: 'M-003',
      line: 'Line 2 - Stamping & Heavy Fabrication',
      durationHours: 7.0,
      scheduledStart: '2026-09-26T09:00:00',
      scheduledEnd: '2026-09-26T16:00:00',
      status: 'in_progress',
      progressPct: 80,
      delayHours: 0,
      requiredSkill: 'Heavy Press Tooling',
    },
    {
      id: 'OP-35',
      name: 'Turbine Housing CMM Micron Inspection',
      orderId: 'ORDER-1040',
      machineId: 'M-005',
      line: 'Line 3 - Quality Assurance & Metrology',
      durationHours: 3.0,
      scheduledStart: '2026-09-26T15:00:00',
      scheduledEnd: '2026-09-26T18:00:00',
      status: 'scheduled',
      progressPct: 0,
      delayHours: 0,
      requiredSkill: 'Zeiss Calypso CMM Programming',
    },
  ];

  for (const op of operationsData) {
    await prisma.operation.create({ data: op });
  }

  // 5. Inventory Items
  const inventoryData = [
    {
      id: 'SP-104',
      name: 'High-Precision Ceramic Spindle Bearing (ISO P2)',
      category: 'spare_part',
      unit: 'sets',
      onHand: 2,
      reserved: 0,
      available: 2,
      reorderPoint: 2,
      leadTimeDays: 7,
      unitCostUsd: 1450,
      daysOfCover: 14,
      stockoutRisk: 'medium',
      storageLocation: 'Secure Toolroom Cage B-02',
      relatedMachineId: 'M-004',
      description: 'Matched hybrid ceramic angular contact bearing set (7014C). Critical spare for Makino M-004 high-speed spindle overhaul.',
    },
    {
      id: 'MAT-021',
      name: 'Aerospace Grade 5 Titanium Billet 180mm',
      category: 'raw_material',
      unit: 'kg',
      onHand: 420,
      reserved: 380,
      available: 40,
      reorderPoint: 150,
      leadTimeDays: 14,
      unitCostUsd: 85,
      daysOfCover: 3.5,
      stockoutRisk: 'high',
      storageLocation: 'Raw Stock Rack A-12',
      description: 'Ti-6Al-4V vacuum-arc remelted billet. Used for ORDER-1042 turbine impellers and ORDER-1045 gimbal brackets.',
    },
    {
      id: 'SP-108',
      name: 'Direct-Drive High-Resolution Rotary Encoder Ring',
      category: 'spare_part',
      unit: 'units',
      onHand: 4,
      reserved: 0,
      available: 4,
      reorderPoint: 2,
      leadTimeDays: 10,
      unitCostUsd: 890,
      daysOfCover: 28,
      stockoutRisk: 'low',
      storageLocation: 'Electrical Spares Drawer E-05',
      relatedMachineId: 'M-001',
      description: 'Optical incremental ring encoder for 5-axis rotary table positioning.',
    },
    {
      id: 'SP-112',
      name: 'Through-Spindle Coolant Rotary Union Seal Kit',
      category: 'spare_part',
      unit: 'kits',
      onHand: 6,
      reserved: 1,
      available: 5,
      reorderPoint: 3,
      leadTimeDays: 5,
      unitCostUsd: 320,
      daysOfCover: 21,
      stockoutRisk: 'low',
      storageLocation: 'Hydraulics Rack H-08',
      relatedMachineId: 'M-004',
      description: 'Silicon carbide dynamic seals rated for 70 bar high-pressure through-spindle coolant.',
    },
    {
      id: 'MAT-018',
      name: 'Inconel 718 High-Temp Nickel Alloy Bar',
      category: 'raw_material',
      unit: 'kg',
      onHand: 650,
      reserved: 300,
      available: 350,
      reorderPoint: 200,
      leadTimeDays: 18,
      unitCostUsd: 110,
      daysOfCover: 22,
      stockoutRisk: 'low',
      storageLocation: 'High-Temp Alloy Bay C-01',
      description: 'Heat-resistant nickel superalloy for gas turbine stator rings (ORDER-1046).',
    },
    {
      id: 'COMP-301',
      name: 'Bosch Rexroth Proportional Hydraulic Directional Valve',
      category: 'component',
      unit: 'units',
      onHand: 14,
      reserved: 4,
      available: 10,
      reorderPoint: 5,
      leadTimeDays: 12,
      unitCostUsd: 1280,
      daysOfCover: 25,
      stockoutRisk: 'low',
      storageLocation: 'Hydraulics Rack H-02',
      relatedMachineId: 'M-003',
      description: 'Electro-hydraulic servo valve for 500T press ram velocity profiling.',
    },
    {
      id: 'TOOL-502',
      name: 'Solid Carbide 5-Flute Endmill 16mm AlTiN',
      category: 'component',
      unit: 'units',
      onHand: 48,
      reserved: 24,
      available: 24,
      reorderPoint: 20,
      leadTimeDays: 4,
      unitCostUsd: 145,
      daysOfCover: 16,
      stockoutRisk: 'low',
      storageLocation: 'Automatic Tool Dispenser ATC-1',
      description: 'High-performance roughing and finishing endmill for titanium and stainless steels.',
    },
    {
      id: 'SP-119',
      name: 'Spindle Drive Timing Belt HDT-8M',
      category: 'spare_part',
      unit: 'units',
      onHand: 5,
      reserved: 0,
      available: 5,
      reorderPoint: 2,
      leadTimeDays: 6,
      unitCostUsd: 180,
      daysOfCover: 35,
      stockoutRisk: 'low',
      storageLocation: 'Mechanical Spares Drawer M-03',
      description: 'Reinforced polyurethane synchronous drive belt for auxiliary spindle gearbox.',
    },
  ];

  for (const item of inventoryData) {
    await prisma.inventoryItem.create({ data: item });
  }

  // 6. Inventory Transactions
  const transactionsData = [
    {
      id: 'TX-1092',
      timestamp: '2026-09-26T10:15:00',
      itemId: 'MAT-021',
      itemName: 'Aerospace Grade 5 Titanium Billet 180mm',
      type: 'issue',
      quantity: 60,
      referenceType: 'production_order',
      referenceId: 'ORDER-1042',
      performedBy: 'Zoe Martinez',
      notes: 'Issued material batch #T-9921 for OP-27 turbine impeller production.',
    },
    {
      id: 'TX-1093',
      timestamp: '2026-09-26T11:30:00',
      itemId: 'TOOL-502',
      itemName: 'Solid Carbide 5-Flute Endmill 16mm AlTiN',
      type: 'issue',
      quantity: 4,
      referenceType: 'production_order',
      referenceId: 'OP-24',
      performedBy: 'Elena Chen',
      notes: 'Replacement tooling for 5-axis titanium roughing cycle.',
    },
    {
      id: 'TX-1094',
      timestamp: '2026-09-26T12:45:00',
      itemId: 'SP-104',
      itemName: 'High-Precision Ceramic Spindle Bearing (ISO P2)',
      type: 'reservation',
      quantity: 1,
      referenceType: 'work_order',
      referenceId: 'WO-204',
      performedBy: 'NOVA Automated Safety Dispatch',
      notes: 'Pre-reserved for pending M-004 corrective spindle overhaul work order.',
    },
  ];

  for (const tx of transactionsData) {
    await prisma.inventoryTransaction.create({ data: tx });
  }

  // 7. Purchase Orders
  const purchaseOrdersData = [
    {
      id: 'PO-901',
      supplier: 'CeramTec Precision Bearing GmbH',
      itemId: 'SP-104',
      itemName: 'High-Precision Ceramic Spindle Bearing (ISO P2)',
      quantity: 4,
      unitPriceUsd: 1450,
      totalPriceUsd: 5800,
      orderDate: '2026-09-22',
      expectedDelivery: '2026-09-29',
      status: 'order_placed',
      risk: 'low',
      riskNotes: 'Confirmed in factory final QA. Tracking carrier DHL Express Air.',
    },
    {
      id: 'PO-902',
      supplier: 'Apex Titanium Forgings International',
      itemId: 'MAT-021',
      itemName: 'Aerospace Grade 5 Titanium Billet 180mm',
      quantity: 500,
      unitPriceUsd: 85,
      totalPriceUsd: 42500,
      orderDate: '2026-09-18',
      expectedDelivery: '2026-09-30',
      status: 'in_transit',
      risk: 'medium',
      riskNotes: 'Customs port clearance delay estimated at +36 hours. Monitored for ORDER-1045 impact.',
    },
    {
      id: 'PO-903',
      supplier: 'Freudenberg Sealing Technologies',
      itemId: 'SP-112',
      itemName: 'Through-Spindle Coolant Rotary Union Seal Kit',
      quantity: 10,
      unitPriceUsd: 320,
      totalPriceUsd: 3200,
      orderDate: '2026-09-15',
      expectedDelivery: '2026-09-24',
      status: 'delivered',
      risk: 'low',
      riskNotes: 'Goods received and inspected at Bay 4 dock.',
    },
    {
      id: 'PO-904',
      supplier: 'Kennametal Industrial Tools',
      itemId: 'TOOL-502',
      itemName: 'Solid Carbide 5-Flute Endmill 16mm AlTiN',
      quantity: 50,
      unitPriceUsd: 145,
      totalPriceUsd: 7250,
      orderDate: '2026-09-25',
      expectedDelivery: '2026-09-29',
      status: 'approved',
      risk: 'low',
      riskNotes: 'Standard 4-day replenishment cycle.',
    },
  ];

  for (const po of purchaseOrdersData) {
    await prisma.purchaseOrder.create({ data: po });
  }

  // 8. Maintenance Work Orders
  const workOrdersData = [
    {
      id: 'WO-204',
      machineId: 'M-004',
      machineName: 'Makino Multi-Spindle High-Speed Milling Cell',
      issue: 'Abnormal spindle bearing vibration (4.85 mm/s > 3.20 mm/s prototype threshold). Cage harmonics detected at 1,840 Hz.',
      priority: 'critical',
      type: 'corrective',
      technicianId: 'EMP-01',
      technicianName: 'Marcus Vance',
      requiredSkill: 'CNC Vibration Diagnostics Level 3',
      sparePartsChecked: true,
      status: 'open',
      created: '2026-09-26T12:30:00',
      dueDate: '2026-09-27T08:00:00',
      estimatedDurationHours: 6.5,
      notes: 'Spindle bearing replacement required. Vibration telemetry demonstrates accelerated degradation. Failure to act within 8h creates high risk of catastrophic spindle seizure.',
      sparePartIds: ['SP-104'],
    },
    {
      id: 'WO-201',
      machineId: 'M-002',
      machineName: 'DMG Mori Precision Turning Lathe',
      issue: 'Quarterly hydraulic filter replacement & way-lube pressure calibration',
      priority: 'medium',
      type: 'preventive',
      technicianId: 'EMP-03',
      technicianName: 'David Kalu',
      requiredSkill: 'Hydraulics',
      sparePartsChecked: true,
      status: 'in_progress',
      created: '2026-09-26T08:00:00',
      dueDate: '2026-09-26T16:00:00',
      estimatedDurationHours: 3.0,
      notes: 'Routine 500-hour service interval. Filter pressure drop nominal.',
      sparePartIds: ['SP-112'],
    },
    {
      id: 'WO-203',
      machineId: 'M-003',
      machineName: 'Schuler Automated 500T Stamping Press',
      issue: 'Pressure transducer zero-drift recalibration',
      priority: 'low',
      type: 'preventive',
      technicianId: 'EMP-05',
      technicianName: 'Tomasz Nowak',
      requiredSkill: 'PLC Troubleshooting',
      sparePartsChecked: true,
      status: 'completed',
      created: '2026-09-25T14:00:00',
      dueDate: '2026-09-25T18:00:00',
      estimatedDurationHours: 2.0,
      actualDurationHours: 1.8,
      notes: 'Recalibrated via Beckhoff TwinCAT diagnostic console. Drift within 0.2% tolerance.',
      sparePartIds: [],
    },
  ];

  for (const wo of workOrdersData) {
    const { sparePartIds, ...woFields } = wo;
    await prisma.maintenanceWorkOrder.create({ data: woFields });
    for (const partId of sparePartIds) {
      await prisma.workOrderSparePart.create({
        data: {
          workOrderId: wo.id,
          sparePartId: partId,
        },
      });
    }
  }

  // 9. Quality Inspections
  const qualityData = [
    {
      id: 'QI-404',
      timestamp: '2026-09-26T12:00:00',
      machineId: 'M-004',
      machineName: 'Makino Multi-Spindle High-Speed Milling Cell',
      line: 'Line 2 - Stamping & Heavy Fabrication',
      batchId: 'BATCH-8821',
      productId: 'PROD-TI-01',
      productName: 'Titanium Turbine Impeller Array v4',
      inspectedUnits: 40,
      defectUnits: 3,
      defectRatePpm: 75000,
      spcSignal: 'out_of_control',
      status: 'warning',
      defectsJson: JSON.stringify([
        { type: 'Spindle chatter wave marks (Ra > 0.8µm)', count: 2 },
        { type: 'Micro-burr on trailing edge vane', count: 1 },
      ]),
      correctiveActionId: 'WO-204',
    },
    {
      id: 'QI-401',
      timestamp: '2026-09-26T11:00:00',
      machineId: 'M-001',
      machineName: 'Hermle 5-Axis CNC Mill Alpha',
      line: 'Line 1 - High-Precision Milling',
      batchId: 'BATCH-8819',
      productId: 'PROD-TH-02',
      productName: 'Stage 2 Turbine Housing',
      inspectedUnits: 25,
      defectUnits: 0,
      defectRatePpm: 0,
      spcSignal: 'in_control',
      status: 'passed',
      defectsJson: JSON.stringify([]),
    },
    {
      id: 'QI-402',
      timestamp: '2026-09-26T10:30:00',
      machineId: 'M-002',
      machineName: 'DMG Mori Precision Turning Lathe',
      line: 'Line 1 - High-Precision Milling',
      batchId: 'BATCH-8818',
      productId: 'PROD-HC-04',
      productName: 'Hydraulic Core Cylinder',
      inspectedUnits: 60,
      defectUnits: 1,
      defectRatePpm: 16666,
      spcSignal: 'in_control',
      status: 'passed',
      defectsJson: JSON.stringify([{ type: 'Thread lead minor deviation', count: 1 }]),
    },
  ];

  for (const qi of qualityData) {
    await prisma.qualityInspection.create({ data: qi });
  }

  // 10. Alerts
  const alertsData = [
    {
      id: 'AL-101',
      priority: 'critical',
      issue: 'Machine M-004 abnormal spindle vibration (4.85 mm/s > 3.20 mm/s prototype threshold)',
      impact: 'Accelerated bearing wear, surface chatter defect rate at 75,000 PPM, and imminent schedule disruption for ORDER-1042 (₹2,45,000 value at risk).',
      owner: 'Marcus Vance (Senior Diagnostic Specialist)',
      recommendedAction: 'Execute corrective maintenance WO-204 and simulate schedule reroute to standby cell M-006.',
      status: 'active',
      timestamp: '2026-09-26T12:45:00',
      relatedModule: 'machines',
      targetId: 'M-004',
    },
    {
      id: 'AL-102',
      priority: 'high',
      issue: 'Customer Delivery Risk: ORDER-1042 (SkyVector Aerospace)',
      impact: 'Buffer to contractual delivery SLA collapsed to 1.5h due to M-004 cycle delay. Contractual penalty of ₹18,500/day applies.',
      owner: 'Liam O’Connor (Production Scheduler)',
      recommendedAction: 'Open What-If Simulator and evaluate re-allocating OP-27 to standby CNC M-006.',
      status: 'active',
      timestamp: '2026-09-26T13:00:00',
      relatedModule: 'orders',
      targetId: 'ORDER-1042',
    },
    {
      id: 'AL-103',
      priority: 'medium',
      issue: 'Inventory Low Buffer: Titanium Billet MAT-021',
      impact: 'Available stock (40 kg) below reorder safety buffer (150 kg). PO-902 delayed in customs transit.',
      owner: 'Zoe Martinez (Logistics)',
      recommendedAction: 'Contact Apex Titanium Forgings to expedite customs dispatch or hold non-priority reservation.',
      status: 'acknowledged',
      timestamp: '2026-09-26T11:15:00',
      relatedModule: 'inventory',
      targetId: 'MAT-021',
    },
    {
      id: 'AL-104',
      priority: 'low',
      issue: 'Preventive Maintenance Due: M-003 Stamping Press',
      impact: 'Scheduled 500-hour hydraulic oil filtration due in 48 hours.',
      owner: 'David Kalu (Maintenance)',
      recommendedAction: 'Confirm maintenance window during upcoming shift changeover.',
      status: 'acknowledged',
      timestamp: '2026-09-26T09:00:00',
      relatedModule: 'maintenance',
      targetId: 'M-003',
    },
  ];

  for (const alert of alertsData) {
    await prisma.alert.create({ data: alert });
  }

  // 11. Recommendations
  const recommendationsData = [
    {
      id: 'REC-01',
      title: 'Machine M-004 Spindle Overhaul & Production Schedule Reroute',
      priority: 'critical',
      targetEntity: 'M-004 / OP-27 / ORDER-1042',
      category: 'machine_health',
      what: 'Machine M-004 spindle vibration reached 4.85 mm/s, exceeding safety envelope (+51.6% above baseline). Inspection QI-404 confirmed micro-chatter marks.',
      why: 'Continued operation risks catastrophic spindle bearing seizure (₹35,000 rebuild cost) and guaranteed failure of ₹2,45,000 SkyVector Aerospace customer order.',
      evidence: '4-hour telemetry trend exhibits sharp exponential ramp from 2.95 mm/s to 4.85 mm/s; Quality inspection batch B-8821 rejected 2 out of 40 units for Ra finish > 0.8µm.',
      method: 'Prototype threshold-based telemetry anomaly detection & dynamic schedule dependency graph analysis.',
      recommendedAction: 'Take M-004 offline for 6.5h bearing replacement; dispatch Marcus Vance with reserved part SP-104; reroute remaining OP-27 finishing to Standby Cell M-006.',
      estimatedImpact: 'Prevents estimated ₹48,000 in unscheduled downtime and SLA late penalties; preserves 100% on-time delivery for ORDER-1042.',
      status: 'pending',
      actionType: 'reroute_operation',
      actionPayloadJson: JSON.stringify({
        machineId: 'M-004',
        workOrderId: 'WO-204',
        operationId: 'OP-27',
        targetMachineId: 'M-006',
      }),
    },
    {
      id: 'REC-02',
      title: 'Titanium Billet MAT-021 Expedited Replenishment',
      priority: 'high',
      targetEntity: 'MAT-021 / PO-902',
      category: 'material_shortage',
      what: 'Available inventory for Titanium Billet MAT-021 stands at 40 kg against 150 kg minimum reorder safety margin.',
      why: 'Upcoming order ORDER-1045 for Stratos Satellite Labs requires 120 kg within 48 hours. Supplier shipment PO-902 faces +36h customs clearance delay.',
      evidence: 'Real-time inventory reserve consumption ledger; Automated customs tracking API alert from DHL Freight.',
      method: 'Dynamic days-of-cover burn rate calculation vs procurement lead-time delta.',
      recommendedAction: 'Trigger air-freight hot-shot expediting fee (₹650) to clear port shipment PO-902 priority lane.',
      estimatedImpact: 'Eliminates 3-day production freeze on Line 1; protects ₹1,40,000 revenue.',
      status: 'pending',
      actionType: 'expedite_procurement',
      actionPayloadJson: JSON.stringify({
        poId: 'PO-902',
      }),
    },
  ];

  for (const rec of recommendationsData) {
    await prisma.decisionRecommendation.create({ data: rec });
  }

  // 12. WhatIfScenario
  const scenarioData = {
    id: 'SCENARIO-01',
    title: 'M-004 Bearing Overhaul + Reroute OP-27 to Standby M-006',
    description: 'Test operational consequences of pulling M-004 for a 6.5h maintenance window while dynamically rerouting finishing operations to Mazak Standby Cell M-006.',
    type: 'machine_offline',
    parametersJson: JSON.stringify({
      machineId: 'M-004',
      downtimeHours: 6.5,
      rerouteToMachineId: 'M-006',
      expediteSparePart: true,
    }),
    currentMetricsJson: JSON.stringify({
      productionOutputUnits: 432,
      oeePct: 78.4,
      activeOrders: 8,
      ordersAtRisk: 2,
      machineAvailabilityPct: 83.3,
      estimatedDowntimeHours: 14.5,
      laborOvertimeCostUsd: 4200,
      totalCostUsd: 84600,
      onTimeDeliveryPct: 75.0,
    }),
    simulatedMetricsJson: JSON.stringify({
      productionOutputUnits: 486,
      oeePct: 88.2,
      activeOrders: 8,
      ordersAtRisk: 0,
      machineAvailabilityPct: 94.0,
      estimatedDowntimeHours: 6.5,
      laborOvertimeCostUsd: 1800,
      totalCostUsd: 52400,
      onTimeDeliveryPct: 100.0,
    }),
    impactChainJson: JSON.stringify([
      { stage: 'Machine Telemetry', description: 'M-004 taken offline cleanly under scheduled maintenance window.', severity: 'nominal' },
      { stage: 'Maintenance Dispatch', description: 'WO-204 assigned to Marcus Vance; SP-104 issued from stock.', severity: 'nominal' },
      { stage: 'Line Capacity Reroute', description: 'OP-27 finishing transferred to Mazak M-006 standby cell.', severity: 'nominal' },
      { stage: 'Production Schedule', description: 'Timeline recovered: OP-27 completes with +2.5h delivery buffer margin.', severity: 'nominal' },
      { stage: 'Customer Orders', description: 'ORDER-1042 and ORDER-1048 risk downgraded from HIGH to LOW.', severity: 'nominal' },
      { stage: 'Financial Outcome', description: '₹32,200 net operational savings; SLA late penalties avoided.', severity: 'nominal' },
    ]),
    consequencesJson: JSON.stringify({
      affectedOperations: ['OP-27', 'OP-28'],
      affectedOrders: ['ORDER-1042', 'ORDER-1048'],
      costDeltaUsd: -32200,
      delayDeltaHours: -5.5,
      oeeDeltaPct: 9.8,
    }),
  };

  await prisma.whatIfScenario.create({ data: scenarioData });

  // 13. App Users
  const usersData = [
    {
      id: 'user-admin',
      name: 'Admin User',
      email: 'admin.user@novacommand.io',
      role: 'ADMIN',
      title: 'System Administrator & Plant Director',
      initials: 'AU',
      department: 'Executive Operations',
      avatarBg: 'bg-purple-600 text-white',
      description: 'Full access to all application modules, data, configurations, and user management.',
    },
    {
      id: 'user-manager',
      name: 'Manager User',
      email: 'manager.user@novacommand.io',
      role: 'MANAGER',
      title: 'Operations & Production Manager',
      initials: 'MU',
      department: 'Shop Floor Operations',
      avatarBg: 'bg-blue-600 text-white',
      description: 'Access to operational modules: Command Center, Production, Factory Floor, Machines, Maintenance, Inventory, Procurement, Analytics.',
    },
    {
      id: 'user-hr',
      name: 'HR User',
      email: 'hr.user@novacommand.io',
      role: 'HR',
      title: 'Human Resources & People Operations',
      initials: 'HR',
      department: 'Human Resources',
      avatarBg: 'bg-emerald-600 text-white',
      description: 'Access to Command Center, Workforce, employee information, and HR analytics.',
    },
  ];

  for (const u of usersData) {
    await prisma.appUser.create({ data: u });
  }

  // 14. System State
  await prisma.systemState.create({
    data: {
      id: 'singleton',
      committedPlanVersion: 1,
      plantShift: 'Shift A (06:00 - 14:00)',
      plantTime: '13:42:15',
      lastUpdated: 'Simulated Telemetry Stream (Active)',
      demoStep: 1,
      selectedMachineId: 'M-004',
      selectedOrderId: 'ORDER-1042',
    },
  });

  console.log('--- NOVA COMMAND Database Seeding Completed Successfully ---');
}

if (require.main === module) {
  seedDatabase()
    .then(async () => {
      await prisma.$disconnect();
    })
    .catch(async (e) => {
      console.error('Error during database seed:', e);
      await prisma.$disconnect();
      process.exit(1);
    });
}
